name: "Azure Blob Storage Upload"
author: "Conrad Haupt <conrad@conradhaupt.com"
description: "Uploads assets to Azure Blob Storage"
branding:
  icon: "box"
  color: "green"
inputs:
  cli_version:
    description: "If set, specifies the version of the Azure CLI to install. Defaults to latest"
    required: false
  container_name:
    description: "The name of the storage account container these assets will be uploaded to"
    required: true
  source_dir:
    description: "The name of the directory you want to upload"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
